#!/usr/bin/env bash

set -Eeuo pipefail

BRANCH="${MACULUS_BRANCH:-main}"
REMOTE="${MACULUS_REMOTE:-origin}"
XCODE_JOBS="${MACULUS_XCODE_JOBS:-4}"
OUTPUT_DIR="${MACULUS_OUTPUT_DIR:-$HOME/Downloads}"
SYNC_FROM_GITHUB=1

case "${1:-}" in
  "") ;;
  --no-sync) SYNC_FROM_GITHUB=0 ;;
  *)
    echo "Usage: $0 [--no-sync]" >&2
    exit 2
    ;;
esac

log() {
  printf '\n==> %s\n' "$1"
}

fail() {
  printf '\nERROR: %s\n' "$1" >&2
  exit 1
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

[[ "$(uname -s)" == "Darwin" ]] || fail "This script must run on macOS."

for command_name in git node npm ruby bundle xcodebuild python3 zip unzip plutil shasum; do
  command_exists "$command_name" || fail "Required command is missing: $command_name"
done

REPOSITORY_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" ||
  fail "Run this inside the Maculus Git repository."

if [[ -f "$REPOSITORY_ROOT/MaculusApp/package.json" ]]; then
  APP_ROOT="$REPOSITORY_ROOT/MaculusApp"
elif [[ -f "$REPOSITORY_ROOT/package.json" ]]; then
  APP_ROOT="$REPOSITORY_ROOT"
else
  fail "Could not find the MaculusApp package from $REPOSITORY_ROOT"
fi

cd "$REPOSITORY_ROOT"
CURRENT_BRANCH="$(git branch --show-current)"

if [[ "$SYNC_FROM_GITHUB" -eq 1 ]]; then
  [[ "$CURRENT_BRANCH" == "$BRANCH" ]] ||
    fail "Switch to '$BRANCH' before syncing. Current branch: '$CURRENT_BRANCH'"
  [[ -z "$(git status --porcelain --untracked-files=no)" ]] ||
    fail "Tracked files have local changes. Commit or stash them before syncing."

  log "Fast-forwarding from $REMOTE/$BRANCH"
  git fetch "$REMOTE" "$BRANCH"
  git merge --ff-only "$REMOTE/$BRANCH"
fi

ACTIVE_DEVELOPER_DIR="$(xcode-select -p 2>/dev/null || true)"
[[ "$ACTIVE_DEVELOPER_DIR" == *"Xcode.app/Contents/Developer"* ]] ||
  fail "Full Xcode is not selected. Run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if (( NODE_MAJOR < 18 )); then
  fail "Maculus requires Node 18 or newer. Current version: $(node --version)"
fi

cd "$APP_ROOT"

export RNLLAMA_BUILD_FROM_SOURCE=1
export RNLLAMA_SKIP_POSTINSTALL=1
export RCT_NEW_ARCH_ENABLED=1
export USE_THIRD_PARTY_JSC=1
export USE_HERMES=0

# Record clean tracked project files before CocoaPods gets a chance to rewrite
# them. The cleanup trap later restores only files that were clean here, so a
# build never overwrites genuine user edits or leaves generated pull conflicts.
GENERATED_TRACKED_FILES=(
  "MaculusApp/ios/MaculusApp.xcodeproj/project.pbxproj"
)
# macOS ships Bash 3.2, where expanding an empty array under `set -u` raises an
# unbound-variable error. Keep one empty sentinel and skip it during cleanup.
GENERATED_TRACKED_CLEAN_AT_START=("")
for generated_file in "${GENERATED_TRACKED_FILES[@]}"; do
  if git -C "$REPOSITORY_ROOT" ls-files --error-unmatch "$generated_file" >/dev/null 2>&1 &&
    git -C "$REPOSITORY_ROOT" diff --quiet -- "$generated_file" &&
    git -C "$REPOSITORY_ROOT" diff --cached --quiet -- "$generated_file"; then
    GENERATED_TRACKED_CLEAN_AT_START+=("$generated_file")
  fi
done

cleanup_generated_project() {
  for generated_file in "${GENERATED_TRACKED_CLEAN_AT_START[@]}"; do
    [[ -n "$generated_file" ]] || continue
    if ! git -C "$REPOSITORY_ROOT" diff --quiet -- "$generated_file"; then
      git -C "$REPOSITORY_ROOT" restore -- "$generated_file" || true
    fi
  done
}
trap cleanup_generated_project EXIT

PACKAGE_INPUT_HASH="$(shasum -a 256 package-lock.json patches/*.patch | shasum -a 256 | awk '{print $1}')"
PACKAGE_INSTALL_STAMP="node_modules/.maculus-package-lock.sha256"
if [[ ! -d node_modules/react-native ]] ||
  [[ ! -f "$PACKAGE_INSTALL_STAMP" ]] ||
  [[ "$(<"$PACKAGE_INSTALL_STAMP")" != "$PACKAGE_INPUT_HASH" ]]; then
  log "Installing JavaScript dependencies"
  npm ci --no-audit --no-fund
  printf '%s\n' "$PACKAGE_INPUT_HASH" > "$PACKAGE_INSTALL_STAMP"
else
  log "JavaScript dependencies and local package patches are current"
fi

log "Installing CocoaPods dependencies and the local iOS vision modules"
bundle config set --local path vendor/bundle
bundle install --jobs 4 --retry 2
(
  cd ios

  # Podfile.lock is intentionally ignored because the native dependency graph
  # follows the checked-in React Native version. A lock generated by an older
  # checkout can otherwise pin incompatible transitive pods (for example,
  # SocketRocket 0.7.0 after upgrading to React Native 0.81).
  if [[ -f Podfile.lock ]] && grep -q 'SocketRocket (= 0\.7\.0)' Podfile.lock; then
    log "Removing the stale local CocoaPods lock"
    rm -f Podfile.lock
  fi

  bundle exec pod install
)

# React Native's Xcode phase needs the same Node binary selected by this shell.
printf 'export NODE_BINARY="%s"\n' "$(command -v node)" > ios/.xcode.env.local

WORKSPACE="$(find "$APP_ROOT/ios" -maxdepth 1 -name "*.xcworkspace" -print -quit)"
[[ -n "$WORKSPACE" ]] || fail "CocoaPods did not generate an iOS workspace."

SCHEME_JSON="$(xcodebuild -workspace "$WORKSPACE" -list -json)"
SCHEME="$(printf '%s' "$SCHEME_JSON" | python3 -c '
import json
import sys

schemes = json.load(sys.stdin)["workspace"]["schemes"]
print(next((item for item in schemes if item.lower() == "maculusapp"), schemes[0] if schemes else ""))
'
)"
[[ -n "$SCHEME" ]] || fail "Could not determine the Maculus Xcode scheme."

LOG_DIR="$APP_ROOT/tmp"
BUILD_LOG="$LOG_DIR/ios-unsigned-build.log"
mkdir -p "$LOG_DIR" "$OUTPUT_DIR"
DERIVED_DATA="${MACULUS_DERIVED_DATA:-$APP_ROOT/ios/build/unsigned-derived-data}"
mkdir -p "$DERIVED_DATA"
touch "$DERIVED_DATA/.metadata_never_index"
IPA_TEMP="$(mktemp -d "${TMPDIR:-/tmp}/maculus-ios-ipa.XXXXXX")"

cleanup() {
  rm -rf "$IPA_TEMP"
  cleanup_generated_project
}
trap cleanup EXIT

log "Building unsigned Maculus for a physical iPhone with scheme '$SCHEME'"

set +e
xcodebuild \
  -workspace "$WORKSPACE" \
  -scheme "$SCHEME" \
  -configuration Release \
  -sdk iphoneos \
  -destination "generic/platform=iOS" \
  -derivedDataPath "$DERIVED_DATA" \
  -jobs "$XCODE_JOBS" \
  CODE_SIGNING_ALLOWED=NO \
  CODE_SIGNING_REQUIRED=NO \
  DEVELOPMENT_TEAM="" \
  RCT_NEW_ARCH_ENABLED=1 \
  USE_THIRD_PARTY_JSC=1 \
  USE_HERMES=0 \
  COMPILER_INDEX_STORE_ENABLE=NO \
  build 2>&1 | tee "$BUILD_LOG"
XCODE_STATUS=${PIPESTATUS[0]}
set -e

if [[ "$XCODE_STATUS" -ne 0 ]]; then
  printf '\nFirst relevant Xcode errors:\n'
  grep -nE \
    -B 6 -A 12 \
    "Undefined symbols|duplicate symbol|symbol\(s\) not found|library .* not found|framework .* not found|Could not find or use auto-linked|error:|fatal error:|Killed|too many open files|No space left|unable to execute command" \
    "$BUILD_LOG" | head -120 || true
  fail "Xcode build failed. Full log: $BUILD_LOG"
fi

APP="$(find "$DERIVED_DATA/Build/Products/Release-iphoneos" -maxdepth 1 -name "*.app" -print -quit)"
[[ -d "$APP" ]] || fail "Build succeeded but no Release iPhoneOS .app was found."
[[ ! -d "$APP/Frameworks/hermes.framework" ]] ||
  fail "Built app still contains Hermes instead of the iOS 27-safe JavaScriptCore runtime."

for model_name in \
  yolo11s.tflite \
  yolo11s.tflite.sha256 \
  yolo11s.tflite.provenance.json \
  depth_anything_v2_small_uint8_256.onnx \
  person_reid_osnet_x0_25.onnx \
  LFM_OPEN_LICENSE.txt \
  lfm2.5-vl-1.6b-q4_k_m.provenance.json \
  melspectrogram.onnx \
  embedding_model.onnx \
  hey_livekit.onnx; do
  find "$APP" -name "$model_name" -print -quit | grep -q . ||
    fail "Built app is missing required offline model: $model_name"
done

YOLO_MODEL="$(find "$APP" -name yolo11s.tflite -print -quit)"
YOLO_CHECKSUM="$(find "$APP" -name yolo11s.tflite.sha256 -print -quit)"
read -r EXPECTED_YOLO_SHA _ < "$YOLO_CHECKSUM"
ACTUAL_YOLO_SHA="$(shasum -a 256 "$YOLO_MODEL")"
ACTUAL_YOLO_SHA="${ACTUAL_YOLO_SHA%% *}"
[[ "$ACTUAL_YOLO_SHA" == "$EXPECTED_YOLO_SHA" ]] ||
  fail "Bundled YOLO model checksum does not match its tracked provenance file."

REID_MODEL="$(find "$APP" -name person_reid_osnet_x0_25.onnx -print -quit)"
REID_CHECKSUM="$(find "$APP" -name person_reid_osnet_x0_25.onnx.sha256 -print -quit)"
[[ -f "$REID_CHECKSUM" ]] || fail "Built app is missing the ReID checksum file."
read -r EXPECTED_REID_SHA _ < "$REID_CHECKSUM"
ACTUAL_REID_SHA="$(shasum -a 256 "$REID_MODEL")"
ACTUAL_REID_SHA="${ACTUAL_REID_SHA%% *}"
[[ "$ACTUAL_REID_SHA" == "$EXPECTED_REID_SHA" ]] ||
  fail "Bundled ReID model checksum does not match its tracked provenance file."

plutil -lint "$APP/Info.plist" >/dev/null

PRIVACY_MANIFEST="$(find "$APP" -name PrivacyInfo.xcprivacy -print -quit)"
[[ -f "$PRIVACY_MANIFEST" ]] || fail "Built app is missing PrivacyInfo.xcprivacy."
plutil -lint "$PRIVACY_MANIFEST" >/dev/null

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
IPA="$OUTPUT_DIR/Maculus-unsigned-$TIMESTAMP.ipa"

log "Packaging and validating the unsigned IPA"
mkdir "$IPA_TEMP/Payload"
cp -R "$APP" "$IPA_TEMP/Payload/"
(
  cd "$IPA_TEMP"
  zip -qry "$IPA" Payload
)
unzip -tq "$IPA"

printf '\nMaculus unsigned IPA created successfully.\n'
printf 'IPA: %s\n' "$IPA"
printf 'Log: %s\n' "$BUILD_LOG"
printf '\nThe IPA still needs an external signer and a valid provisioning profile before installation.\n'
